# Generated by Django 6.0.1 on 2026-02-05 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion_meses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo'), ('FI', 'Finalizado')], default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
